name: Build Docker Image - MP - GT
on:
  workflow_dispatch: 
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Building Docker Image - PUBLIC
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          # 下方的name格式为：Docker Hub ID/自定义镜像名称
          name: '${{ secrets.DOCKER_PATH }}'
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: Building Docker Image - TEST
       # uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          # 下方的name格式为：Docker Hub ID/自定义镜像名称
          name: '${{ secrets.DOCKER_PATH_TEST }}'
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
